name: Build plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching any tag format, i.e. 1.0, 20.15.10

env:
  PLUGIN_NAME: logseq-sort-blocks

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Build
        id: build
        run: |
          pnpm install
          pnpm run build

          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md package.json ${{ env.PLUGIN_NAME }}
          mv dist ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"

      - name: Create Release
        uses: ncipollo/release-action@v1

      - name: Upload zip file
        id: upload_zip
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PLUGIN_NAME }}.zip

      - name: Upload package.json
        id: upload_metadata
        uses: softprops/action-gh-release@v1
        with:
          files: package.json
