name: Build plugin

on:
  push:
    tags:
      - "v*"

env:
  PLUGIN_NAME: logseq-sort-blocks

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Build
        id: build
        run: |
          pnpm install
          pnpm run build

          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md package.json ${{ env.PLUGIN_NAME }}
          mv dist ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            package.json
